import { fc } from "@fast-check/vitest";

// Stryker disable next-line all: filter rarely triggered - __proto__ is almost never generated by fc.string()
const safeKey = fc.string().filter((k) => k !== "__proto__");

/**
 * Arbitrary for safe objects (excludes __proto__ which causes prototype pollution)
 * @internal - Depends on @fast-check/vitest
 */
export const safeObject = (options?: { maxDepth?: number }) =>
    fc.object({
        maxDepth: options?.maxDepth ?? 2,
        key: safeKey,
    });

/**
 * Arbitrary for safe dictionaries (excludes __proto__ which causes prototype pollution)
 * @internal - Depends on @fast-check/vitest
 */
export const safeDictionary = <T>(valueArb: fc.Arbitrary<T>) =>
    fc.dictionary(safeKey, valueArb);