/**
 * Shared emoji map used by the remark plugin (build-time)
 * and the TOC Tree component (client-side).
 */
export const EMOJI_MAP: Record<string, { src: string; alt: string; id?: string }> = {
  "🏺": { src: "/img/generated/logos/pithos-120.png", alt: "pithos" },
  "🅰": { src: "/img/emoji/letter-a.png", alt: "arkhe" },
  "🅺": { src: "/img/emoji/letter-k.png", alt: "kanon" },
  "🆉": { src: "/img/emoji/letter-z.png", alt: "zygos" },
  "🆃": { src: "/img/emoji/letter-t.png", alt: "taphos" },
  "🆂": { src: "/img/emoji/letter-s.png", alt: "Sphalma" },
  "✅": { src: "/img/emoji/checkmark.png", alt: "checkmark" },
  "❌": { src: "/img/emoji/cross.png", alt: "cross" },
  "🔒": { src: "/img/emoji/padlock.png", alt: "padlock"},
  "⚡️": { src: "/img/emoji/flash.png", alt: "flash" },
  "🛡️": { src: "/img/emoji/shield.png", alt: "shield" },
  "📜": { src: "/img/emoji/parchment.png", alt: "parchment" },
  "👁️": { src: "/img/emoji/eye.png", alt: "eye" },
  "🖥️": { src: "/img/emoji/installation.png", alt: "installation" },
  "🛠": { src: "/img/emoji/tools.png", alt: "tools" },
  "⚖️": { src: "/img/emoji/scales.png", alt: "scales" },
  "📋": { src: "/img/emoji/changelog.png", alt: "changelog"},
  "🧱": { src: "/img/emoji/column.png", alt: "basics"},
  "📦": { src: "/img/emoji/two-jars.png", alt: "bundle size", id:"bundle"},
  "🟰": { src: "/img/emoji/twins.png", alt: "equivalence"},
  "🚅": { src: "/img/emoji/speed.png", alt: "performance benchmarks", id:"performance"},
  "⛓️‍💥": { src: "/img/emoji/chain-links.png", alt: "interoperability"},
  "📔": { src: "/img/emoji/book.png", alt: "API reference", id:"api"},
  "🔭": { src: "/img/emoji/telescope.png", alt: "explorer"},
  "🎁": { src: "/img/emoji/cornucopia.png", alt: "Use Cases explorer", id:"usecases"},
  "🎯": { src: "/img/emoji/target.png", alt: "target"},
  "⏮️": { src: "/img/emoji/previous.png", alt: "previous"},
  "⏭️": { src: "/img/emoji/next.png", alt: "next"},
  "✍️": { src: "/img/emoji/parchment-rolled.png", alt: "contract"},
  "🕯️": { src: "/img/emoji/light.png", alt: "read more", id: "read-more"},
  "📎": { src: "/img/emoji/import.png", alt: "import"},
  "🃏" : { src: "/img/emoji/examples.png", alt: "examples"},
  "🎰" : { src: "/img/emoji/treasure.png", alt: "what is the box"},
  
};
