import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const apiSidebars: SidebarsConfig = {
  apiSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default apiSidebars;

